parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Pixiekat\AlicantoConsult\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  Pixiekat\AlicantoConsult\Services\:
    resource: '../src/Services/*'
    public: true
    tags: ['controller.service_arguments']